# Generated by Django 5.2.11 on 2026-02-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_menulink_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='assets/favicon/%Y/%m'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='assets/logo/%Y/%m'),
        ),
    ]
