# Generated by Django 5.2.11 on 2026-02-26 12:22

import utils.model_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_sitesetup_favicon_sitesetup_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='logo',
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='assets/favicon/%Y/%m', validators=[utils.model_validator.validate_png]),
        ),
    ]
