# Generated by Django 5.2.11 on 2026-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0007_remove_sitesetup_show_paginator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='show_pagination',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='show_paginator',
            field=models.BooleanField(default=True),
        ),
    ]
