# Generated by Django 5.2.12 on 2026-03-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='url_externa',
            field=models.URLField(blank=True, default='', help_text='URL externa para a tag. Se preenchida, a tag redirecionará para essa URL em vez de exibir os posts associados.', max_length=255),
        ),
    ]
