# Generated by Django 5.2.12 on 2026-03-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag_url_externa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='nova_aba',
            field=models.BooleanField(default=False),
        ),
    ]
